# ASSIGNMENT QUESTIONS:
# 1) How to create an empty and a full numpy array 

In [1]:
import numpy as np
a=np.empty((4,3,2))
print("Empty array =",a)

Empty array = [[[ 1.68248127e-019  2.10314364e+239]
  [ 7.18826120e-170 -3.47929487e-308]
  [ 1.47088025e-226  2.91913699e-232]]

 [[-1.58592490e-152 -3.43406768e-115]
  [ 6.79964950e-242 -4.69901202e-196]
  [-1.46659145e-152 -3.10294549e+097]]

 [[-1.20569866e+112  5.49647099e-005]
  [-3.55206503e+178  3.97558943e-267]
  [ 2.84217942e-101 -1.22252825e+140]]

 [[ 3.64901540e+017  1.89796723e+051]
  [ 1.14355391e-091  5.93754870e-058]
  [ 6.16371366e-247  6.72738870e-285]]]


In [2]:
b=np.full((2,2),7)
print("Full array =",b)

Full array = [[7 7]
 [7 7]]


# 2) Create a numpy array filled with all zeros

In [6]:
a=np.zeros((4,3))
print("Zeros array =",a)

Zeros array = [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# 3) Create a numpy array filled with all ones

In [31]:
b=np.ones((4,3))
print("Ones array =",b)

Ones array = [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# 4) Check whether a numpy array contains a specified row

In [36]:
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

a = np.array([4, 5, 6])

b = np.any(np.all(array == a, axis=1))

if b:
    print("The specified row exists in the array.")
else:
    print("The specified row does not exist in the array.")

The specified row exists in the array.


# 5) How to remove rows in numpy array that contains non-numeric values

In [39]:
arr1 = np.array([[1, 2, 'g', 3], [4, 8, 5, 6], [7, 8, 'i', 9]])

remove = [0, 2]

arr2 = np.delete(arr1, remove, axis=0)

print("Original Array:")
print(arr1)
print("\nArray after removing specified rows:")
print(arr2)

Original Array:
[['1' '2' 'g' '3']
 ['4' '8' '5' '6']
 ['7' '8' 'i' '9']]

Array after removing specified rows:
[['4' '8' '5' '6']]


# 6) Remove singal dimensional entries from the shape of an array

In [42]:
arr1 = np.array([[[1, 2, 3]]])

print("Original Shape:", arr1.shape)

arr2 = np.ravel(arr1)

print("Shape after changing:", arr2.shape)

Original Shape: (1, 1, 3)
Shape after changing: (3,)


# 7) Find the number of occurences of a sequence in a numpy array

In [47]:
arr = np.array([[2, 8, 9, 4], 
                [9, 4, 9, 4], 
                [4, 5, 9, 7], 
                [2, 9, 4, 3]]) 
 
arr2 = repr(arr).count("9, 4") 

print("Number of occurences of a sequence is",output) 


Number of occurences of a sequence is 4


# 8) Find the most frequent value in a numpy array

In [63]:
arr = np.array([1,2,1,3,6,2,5,1,2,2,3,2,2,5,2,4,2,6,2,5,1,6])
print("Original array =",arr)
arr2 = np.bincount(arr).argmax()
print("Most frequent value in the above array is ",arr2)

Original array = [1 2 1 3 6 2 5 1 2 2 3 2 2 5 2 4 2 6 2 5 1 6]
Most frequent value in the above array is  2


# 9) Combining a one and a two dimensional numpy array

In [68]:
arr1=np.array([1,2,3,4])
arr2=np.array([[1,2,3,4],
               [5,6,7,8]])
arr3=np.vstack([arr1,arr2])
print(arr3)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]]


# 10) How to build an array of all combinations of two numpy arrays

In [76]:
arr1 = np.array([1, 2, 3])
arr2 = np.array(['a', 'b', 'c'])

grid1, grid2 = np.meshgrid(arr1, arr2)

arr3 = np.column_stack((grid1.ravel(), grid2.ravel()))

print("Array 1:",arr1)

print("\nArray 2:",arr2)

print("\nCombined array of all combinations:",arr3)

Array 1: [1 2 3]

Array 2: ['a' 'b' 'c']

Combined array of all combinations: [['1' 'a']
 ['2' 'a']
 ['3' 'a']
 ['1' 'b']
 ['2' 'b']
 ['3' 'b']
 ['1' 'c']
 ['2' 'c']
 ['3' 'c']]
